# AMA-Bench Evaluation Configuration for VLLM

# Model configuration
provider: "vllm"
model: "/raid/lah003/models/Qwen3-32B"

# VLLM server configuration
vllm_host: "localhost"
vllm_port: 8010



enable_thinking: true

# VLLM launch configuration
vllm_launch:
  gpus: "0,1"
  max_model_len: 32000
  max_response_len: 8192
  tensor_parallel_size: 2


